from django.core.management.base import BaseCommand

from survey.models import Choice, Question, QuestionMatrixRow, Region, Sector


class Command(BaseCommand):
    help = 'Seed the demo survey with a starter set of questions and options.'

    def handle(self, *args, **options):
        sectors = [
            ('Banking', 'This section surveys banks licensed by the Bank of Ghana'),
            ('Utilities', 'This section surveys Utilities Sector, including Zoomlion'),
            ('Telecommunications', 'This section surveys licensed Telecom companies in Ghana'),
            ('Hospitality', 'This section surveys hotels that are regulated by the Ghana Tourism Authority'),
            ('Healthcare', 'This section surveys both public and private healthcare facilities'),
            ('Retail Malls', 'This section surveys major retail outlets in Ghana'),
            ('Public Institutions', 'This section surveys public sector institutions in Ghana'),
            ('Online Businesses', 'This section surveys popular e-commerce businesses in Ghana'),
            ('Transportation', 'This section surveys ride hailing transport services in Ghana'),
            ('Insurance', 'This section surveys insurance companies regulated by the National Insurance Commission'),
            ('Oil Marketing Companies', 'This section surveys the Oil Marketing Companies Sector'),
        ]
        for order, (name, description) in enumerate(sectors, start=1):
            Sector.objects.update_or_create(
                name=name,
                defaults={'description': description, 'order': order, 'active': True},
            )

        regions = [
            'Ahafo',
            'Ashanti',
            'Bono East',
            'Bono',
            'Central',
            'Eastern',
            'Greater Accra',
            'North East',
            'Northern',
            'Oti',
            'Savannah',
            'Upper East',
            'Upper West',
            'Volta',
            'Western North',
            'Western',
        ]
        for order, name in enumerate(regions, start=1):
            Region.objects.update_or_create(name=name, defaults={'order': order, 'active': True})

        company_choices = [
            'Absa Bank Ghana Limited',
            'Access Bank (Ghana) Plc',
            'Agricultural Development Bank Limited',
            'Bank of Africa Ghana Limited',
            'CAL Bank Limited',
            'Consolidated Bank Ghana Limited',
            'Ecobank Ghana Limited',
            'FBNBank (Ghana) Limited',
            'Fidelity Bank Ghana Limited',
            'First Atlantic Bank Limited',
            'First National Bank (Ghana) Limited',
            'GCB Bank Limited',
            'GHL Bank Limited',
            'Guaranty Trust Bank (Ghana) Limited',
            'National Investment Bank Limited',
            'OmniBSIC Bank Ghana Limited',
            'Prudential Bank Limited',
            'Republic Bank (Ghana) Limited',
            'Societe General (Ghana) Limited',
            'Stanbic Bank Ghana Limited',
            'Standard Chartered Bank (Ghana) Limited',
            'United Bank for Africa (Ghana) Limited',
            'Universal Merchant Bank Limited',
            'Zenith Bank (Ghana) Limited',
            'Electricity Company of Ghana',
            'Ghana Water Company',
            'Zoomlion Ghana Limited',
            'AirtelTigo',
            'Busy Internet',
            'MTN',
            'Surfline',
            'Teledata ICT',
            'Telecel',
            'Zipnet',
            'Accra City Hotel',
            'Accra Marriot Hotel',
            'Aiport West Hotel',
            'Airport View Hotel',
            'Aqua Safari',
            'Best Western Premier Accra Airport Hotel',
            'Fiesta Royale Hotel',
            'Golden Tulip Accra',
            'Golden Tulip Kumasi City',
            'Holiday Inn Aiport Accra',
            'Ibis Styles Accra Airport City',
            'Kempinski Hotel Gold Coast City',
            'La Palm Royal Beach Hotel',
            'Labadi Beach Hotel',
            'Movenpick Ambassador Hotel Accra',
            'Safari Valley',
            'Swiss Spirit Alisa Hotels North Ridge',
            'The African Regent Hotel',
            'The Royal Senchi',
            '37 Military Hospital',
            # 'Acacia' moved to Insurance
            'Accra Psychiatric Hospital',
            'Achimota Hospital',
            'Aiport Womens Hospital',
            'Del International Hospital',
            'Dodowa District Hospital',
            'Family Health Hospital',
            'Greater Accra Regional Hospital (Ridge Hospital)',
            'Komfo Anokye Teaching Hospital',
            'Korle-Bu Teaching Hospital',
            'Lapaz Community Hospital',
            'LEKMA Hospital',
            'Lister Hospital and Fertility Centre',
            'Nyaho Hospital',
            'Rabito Hospital',
            'St. John\'s Hospital and Fertility Centre',
            'Sunyani Regional Hospital',
            'Tamale Teaching Hospital',
            'University of Ghana Medical Center (UGMC)',
            'Volta Regional Hospital',
            'A&C Mall',
            'Accra Mall',
            'Achimota Retail Centre',
            # 'CityDia' removed (does not exist)
            'Junction Mall',
            'Koala Shopping Mall',
            'Kumasi City Mall',
            'Marina Mall',
            'Max Mart',
            'Melcom',
            'Orca Deco',
            'Oxford Street Mall',
            'Palace Shopping Centre',
            'Takoradi Mall',
            'West Hills Mall',
            'Driver and Vehicle Licensing Authority (DVLA)',
            'Food and Drugs Authority',
            'Ghana Broadcasting Corporation',
            'Ghana Civil Aviation Authority',
            'Ghana Free Zones Board',
            'Ghana Investment Promotion Centre',
            'Ghana Police Service',
            'Ghana Revenue Authority',
            'Ghana Shippers Authority',
            'Ghana Standards Authority',
            'Social Security and National Insurance Trust (SSNIT)',
            'Afrikart',
            'Alibaba Online Shopping Site',
            'Baahe.com',
            'Deus.com.gh',
            'Hubtel Mall',
            'Jumia',
            'Melcome Ghana Online Shopping',
            'Tonaton.com',
            'Zoobashop',
            'Accra Cab',
            'Bolt',
            # 'Dropyn' removed
            # 'Poki Cab' removed
            'Uber',
            'Yango',
            'Acacia',
            'Activa International Insurance Company-Ghana Limited',
            'Allianz Insurance Company Gh. Ltd.',
            'Donewell Insurance Company Limited',
            'Enterprise Insurance Company Limited',
            'Enterprise Life',
            'Glico',
            'GN Life Assurance Limited',
            'Hollard Insurance Ghana Limited',
            'Hollard Life',
            'Imperial General Insurance Company Ltd.',
            'Metropolitan Life Insurance Ghana Limited',
            'NSIA Insurance Company Limited',
            'Provident Insurance Company Limited',
            'Prudential Life Insurance Ghana',
            'Regency Nem Insurance Ghana Limited',
            'SIC Insurance Company Limited',
            'Star Assurance Company Limited',
            'Starlife Assurance Company Limited',
            'Vanguard Assurance Company Limited',
            'Allied',
            'Frimps',
            'Goil',
            'Gulf Energy',
            'Puma',
            'Sel',
            'Shell',
            'Star Oil',
            'Total',
            'Unity Oil',
        ]

        questions = [
            {
                'number': 1,
                'title': 'Please select the sector you want to rate.',
                'question_type': 'radio',
                'choices': [
                    ('Banking', 'Banking'),
                    ('Utilities', 'Utilities'),
                    ('Telecommunications', 'Telecommunications'),
                    ('Hospitality', 'Hospitality'),
                    ('Healthcare', 'Healthcare'),
                    ('Retail Malls', 'Retail Malls'),
                    ('Public Institutions', 'Public Institutions'),
                    ('Online Businesses', 'Online Businesses'),
                    ('Transportation', 'Transportation'),
                    ('Insurance', 'Insurance'),
                    ('Oil Marketing Companies', 'Oil Marketing Companies'),
                ],
            },
            {
                'number': 2,
                'title': 'Overall, how satisfied or dissatisfied are you with customer service in the SELECTED_SECTOR in Ghana?',
                'question_type': 'radio',
                'choices': [(str(i), str(i)) for i in range(1, 8)],
            },
            {
                'number': 3,
                'title': 'Please select ALL_THE_COMPANIES in the SELECTED_SECTOR sector that you have done business with in the last 12 months, even if only once. If the COMPANY_TYPE_SINGULAR is not listed, please type it in the space provided for Others.',
                'question_type': 'checkbox',
                'choices': [(text, text) for text in company_choices],
            },
            {
                'number': 5,
                'title': 'ONE (1) RESPONSE PER ROW. Please select a rating that best describes your extent of satisfaction with your experience with SELECTED_COMPANY in terms of the following, where 1 means totally dissatisfied, and 10 means totally satisfied.',
                'question_type': 'matrix',
                'matrix_rows': [
                    'Trust',
                    'Look and feel',
                    'Competence',
                    'Professionalism',
                    'Ease of doing business',
                    'Processes and procedures',
                    'Customer-focused innovations',
                    'Engagement with customers',
                    'Complaints and feedback',
                    'Health and safety',
                ],
                'choices': [(str(i), str(i)) for i in range(1, 11)],
            },
            {
                'number': 7,
                'title': "Overall, what are your impressions on customer service in Ghana's SELECTED_SECTOR? (Good, Bad, Terrible, Fantastic)",
                'question_type': 'text',
            },
            {
                'number': 8,
                'title': 'As a customer of SELECTED_COMPANY, do you prefer excellent service even if it costs more?',
                'question_type': 'radio',
                'choices': [
                    ('Yes', 'Yes'),
                    ('No', 'No'),
                ],
            },
            {
                'number': 9,
                'title': 'Overall, how satisfied or dissatisfied are you with the customer service of SELECTED_COMPANY?',
                'question_type': 'radio',
                'choices': [(str(i), str(i)) for i in range(1, 8)],
            },
            {
                'number': 10,
                'title': 'How likely are you to recommend SELECTED_COMPANY to a relative, friend or coworker in the future. We shall use a 10 point scale where 0 means very unlikely and 10 very likely.',
                'question_type': 'radio',
                'choices': [(str(i), str(i)) for i in range(0, 11)],
            },
            {
                'number': 11,
                'title': 'What are the most important things you would like to see or want organizations to focus on in future?',
                'question_type': 'checkbox',
                'choices': [
                    ('Personalized experiences', 'Personalized experiences'),
                    ('Proactive communication', 'Proactive communication'),
                    ('Transparency and trust', 'Transparency and trust'),
                    ('Accessibility and inclusivity', 'Accessibility and inclusivity'),
                    ('Value for money and affordability', 'Value for money and affordability'),
                    ('Employee training and improvement', 'Employee training and improvement'),
                    ('Sustainability and social responsibility', 'Sustainability and social responsibility'),
                    ('Continuous improvement', 'Continuous improvement'),
                ],
            },
            {
                'number': 12,
                'title': 'How do you feel about Ghanaian frontline employees who work in customer service roles?',
                'question_type': 'radio',
                'choices': [
                    ('I value their role more', 'I value their role more'),
                    ('I don’t know, I’m indifferent', 'I don’t know, I’m indifferent'),
                    ('I value their role less', 'I value their role less'),
                ],
            },
            {
                'number': 13,
                'title': 'Through which of the following means do you normally interact with SELECTED_COMPANY?',
                'question_type': 'dropdown',
                'choices': [
                    ('Digital Channels', 'Digital Channels'),
                    ('Traditional Channels', 'Traditional Channels'),
                    ('Both Digital and Traditional Channels', 'Both Digital and Traditional Channels'),
                ],
            },
            {
                'number': 14,
                'title': 'Through which of the following specific means do you normally interact with SELECTED_COMPANY?',
                'question_type': 'checkbox',
                'choices': [
                    ('Mobile App', 'Mobile App'),
                    ('Webchat', 'Webchat'),
                    ('Email', 'Email'),
                    ('Text/Over the Phone', 'Text/Over the Phone'),
                    ('Website', 'Website'),
                    ('Social Media', 'Social Media'),
                    ('In Writing', 'In Writing'),
                    ('In Person', 'In Person'),
                ],
            },
            {
                'number': 15,
                'title': 'What is your gender?',
                'question_type': 'radio',
                'choices': [('Male', 'Male'), ('Female', 'Female')],
            },
            {
                'number': 16,
                'title': 'What is your age? Please give your exact age in figures.',
                'question_type': 'text',
            },
            {
                'number': 17,
                'title': 'Which of these brackets do you fall?',
                'question_type': 'radio',
                'choices': [
                    ('Below 18', 'Below 18'),
                    ('18 - 24', '18 - 24'),
                    ('25 - 29', '25 - 29'),
                    ('30 - 34', '30 - 34'),
                    ('35 - 39', '35 - 39'),
                    ('40 - 49', '40 - 49'),
                    ('50 - 59', '50 - 59'),
                    ('60+', '60+'),
                ],
            },
            {
                'number': 18,
                'title': 'Which region do you live in?',
                'question_type': 'radio',
                'choices': [(name, name) for name in regions],
            },
            {
                'number': 19,
                'title': 'What is the highest level of education you have completed?',
                'question_type': 'radio',
                'choices': [
                    ('No Education', 'No Education'),
                    ('Kindergarten', 'Kindergarten'),
                    ('Primary School', 'Primary School'),
                    ('JHS/JSS', 'JHS/JSS'),
                    ('Middle School', 'Middle School'),
                    ('SSS/SHS/Secondary', 'SSS/SHS/Secondary'),
                    ('Vocational/Technical/Commercial', 'Vocational/Technical/Commercial'),
                    ('Teacher Training', 'Teacher Training'),
                    ('Polytechnic', 'Polytechnic'),
                    ('University/Professional', 'University/Professional'),
                ],
            },
            {
                'number': 20,
                'title': 'Into which of the following categories does your monthly personal income fall?',
                'question_type': 'radio',
                'choices': [
                    ('GHS 101 - 1,000', 'GHS 101 - 1,000'),
                    ('GHS 1,001 - 2,000', 'GHS 1,001 - 2,000'),
                    ('GHS 2,001 - 3,000', 'GHS 2,001 - 3,000'),
                    ('GHS 3,001 - 4,000', 'GHS 3,001 - 4,000'),
                    ('GHS 4,001 - 5,000', 'GHS 4,001 - 5,000'),
                    ('GHS 5,001 - 6,000', 'GHS 5,001 - 6,000'),
                    ('GHS 6,001 - 7,000', 'GHS 6,001 - 7,000'),
                    ('GHS 7,001 - 8,000', 'GHS 7,001 - 8,000'),
                    ('GHS 8,001 - 9,000', 'GHS 8,001 - 9,000'),
                    ('GHS 9,001 - 10,000', 'GHS 9,001 - 10,000'),
                    ('More than GHS 10,000', 'More than GHS 10,000'),
                    ("Refused/Don't know", "Refused/Don't know"),
                    ('No Income', 'No Income'),
                ],
            },
            {
                'number': 21,
                'title': 'What is your nationality?',
                'question_type': 'dropdown',
                'choices': [('Ghanaian', 'Ghanaian'), ('Non-Ghanaian', 'Non-Ghanaian')],
            },
            {
                'number': 22,
                'title': 'How did you hear about this survey?',
                'question_type': 'radio',
                'choices': [('Referral', 'Referral'), ('Social Media', 'Social Media'), ('My Organization', 'My Organization')],
            },
            {
                'number': 23,
                'title': 'Please indicate the name of referral.',
                'question_type': 'radio',
                'choices': [(f'Vol. {i}', f'Vol. {i}') for i in range(1, 16)],
            },
            {
                'number': 24,
                'title': 'Would you like to take another survey?',
                'question_type': 'radio',
                'choices': [('Yes', 'Yes'), ('No', 'No')],
            },
        ]

        # Page 4 was a duplicate of the sector company question on page 3.
        Question.objects.filter(number=4).update(active=False)

        for item in questions:
            question, _ = Question.objects.update_or_create(
                number=item['number'],
                defaults={
                    'title': item['title'],
                    'description': item.get('description', ''),
                    'question_type': item['question_type'],
                    'required': True,
                    'order': item['number'],
                    'active': True,
                    'matrix_rows': item.get('matrix_rows', []),
                },
            )
            if item.get('choices'):
                question.choice_set.all().delete()
                for index, (text, value) in enumerate(item['choices'], start=1):
                    Choice.objects.create(question=question, text=text, value=value, order=index, active=True)
            if item['question_type'] == 'matrix':
                question.questionmatrixrow_set.all().delete()
                for index, label in enumerate(item.get('matrix_rows', []), start=1):
                    QuestionMatrixRow.objects.create(question=question, label=label, order=index, active=True)

        self.stdout.write(self.style.SUCCESS('Survey seed data created successfully.'))
